### ISSUE TITLE
Error Getting Credentials

### ISSUE THREAD

**Issue by lavation** [aweber/public-api-examples#64]
In prompt, everything goes smoothly until I paste the returned URL

"Log in and paste the returned URL here:"

`PHP Fatal error:  Uncaught League\OAuth2\Client\Provider\Exception\IdentityProviderException: invalid_request in /opt/bitnami/apache/htdocs/vendor/league/oauth2-client/src/Provider/GenericProvider.php:222
Stack trace:
#0 /opt/bitnami/apache/htdocs/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(628): League\OAuth2\Client\Provider\GenericProvider->checkResponse()
#1 /opt/bitnami/apache/htdocs/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse()
#2 /opt/bitnami/apache/htdocs/getaccess.php(58): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken()
#3 {main}
  thrown in /opt/bitnami/apache/htdocs/vendor/league/oauth2-client/src/Provider/GenericProvider.php on line 222`

**Comment by Neolot** [comment]
Same problem...

**Comment by taherihamid** [comment]
same problem
